package com.cognizant.cognizantits.qcconnection.qcupdation;

public enum TDAPI_NODE_TYPE
{
  NODE_TYPE_UNDEFINED,  NODE_TYPE_RELEASE_FOLDER,  NODE_TYPE_RELEASE,  NODE_TYPE_RELEASECYCLE,  NODE_TYPE_FAVORITE_FOLDER,  NODE_TYPE_FAVORITE,  NODE_TYPE_LIBRARY_FOLDER,  NODE_TYPE_LIBRARY,  NODE_TYPE_LIBRARY_PART,  NODE_TYPE_BASELINE,  NODE_TYPE_QCRESOURCE_FOLDER,  NODE_TYPE_QCRESOURCE,  NODE_TYPE_ANALYSISITEM_FOLDER,  NODE_TYPE_ANALYSISITEM,  NODE_TYPE_DASHBOARD_FOLDER,  NODE_TYPE_DASHBOARD_PAGE,  NODE_TYPE_COMPARISON;
}


/* Location:           D:\Prabu\jars\QC.jar
 * Qualified Name:     qcupdation.TDAPI_NODE_TYPE
 * JD-Core Version:    0.7.0.1
 */