package com.cognizant.cognizantits.qcconnection.qcupdation;

public enum TDAPI_DATATYPES
{
  TDOLE_LONG,  TDOLE_ULONG,  TDOLE_FLOAT,  TDOLE_STRING,  TDOLE_MEMO,  TDOLE_DATE,  TDOLE_TIMESTAMP,  TDOLE_TREENODE,  TDOLE_USER_LIST,  TDOLE_TESTSET_LIST,  TDOLE_HOST_LIST,  TDOLE_SUBJECT_TREENODE,  TDOLE_TESTSET_FOLDER,  TDOLE_REQUIREMENT_TREENODE,  TDOLE_REQUIREMENT_TYPE_ID,  TDOLE_RELEASE_SINGLE_TREENODE,  TDOLE_RELEASE_MULTI_TREENODE,  TDOLE_RELEASECYCLE_SINGLE_TREENODE,  TDOLE_RELEASECYCLE_MULTI_TREENODE,  TDOLE_APPLICATION_ENTITY_FOLDER,  TDOLE_CHANGE_ENTITY_FOLDER,  TDOLE_DataType_SINGLE_TREENODE,  TDOLE_DataType_MULTI_TREENODE,  TDOLE_BASELINES,  TDOLE_TEST_CLASS,  TDOLE_DATETIME,  TDOLE_RESOURCE_FOLDER;
}


/* Location:           D:\Prabu\jars\QC.jar
 * Qualified Name:     qcupdation.TDAPI_DATATYPES
 * JD-Core Version:    0.7.0.1
 */