/*
 * Copyright 2014 - 2017 Cognizant Technology Solutions
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.cognizant.cognizantits.ide.main.ui;

import com.cognizant.cognizantits.datalib.component.TestData;
import com.cognizant.cognizantits.engine.support.DesktopApi;
import com.cognizant.cognizantits.ide.main.mainui.AppMainFrame;
import com.cognizant.cognizantits.ide.util.Notification;
import com.cognizant.cognizantits.ide.util.Validator;
import java.io.File;

/**
 *
 * 
 */
public class ProjectProperties extends javax.swing.JDialog {

    AppMainFrame sMainFrame;

    public ProjectProperties(AppMainFrame sMainFrame) {
        this.sMainFrame = sMainFrame;
        initComponents();
    }

    public void loadForCurrentProject() {

        projectName.setText(sMainFrame.getProject().getName());
        projectLocation.setText(sMainFrame.getProject().getLocation());
        noOfScenarios.setText(sMainFrame.getProject().getScenarios().size() + "");
        int testCaseCount = 0;
        int reusableCaseCount = 0;
        for (int i = 0; i < sMainFrame.getProject().getScenarios().size(); i++) {
            testCaseCount += sMainFrame.getProject().getScenarios().get(i).getTestcaseCount();
            reusableCaseCount += sMainFrame.getProject().getScenarios().get(i).getReusableCount();
        }
        noOfTestCases.setText(String.valueOf(testCaseCount));
        noOfReusables.setText(String.valueOf(reusableCaseCount));
        int tdCount = 0;
        for (TestData testData : sMainFrame.getProject().getTestData().getAllEnvironments()) {
            tdCount += testData.getTestDataList().size();
        }
        noOfTestData.setText(String.valueOf(tdCount));
        openProject.setEnabled(new File(projectLocation.getText()).exists());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        projectLocation = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        noOfScenarios = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        noOfTestCases = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        noOfReusables = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        noOfTestData = new javax.swing.JLabel();
        openProject = new javax.swing.JButton();
        projectName = new javax.swing.JTextField();
        renameProject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ProjectDetails");
        setModal(true);
        setResizable(false);

        jLabel1.setText("Project Name");

        jLabel2.setText("Project Location");

        projectLocation.setEditable(false);
        projectLocation.setText("jTextField2");

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel3.setText("No of Scenarios :");
        jPanel1.add(jLabel3);

        noOfScenarios.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        noOfScenarios.setText("23");
        jPanel1.add(noOfScenarios);

        jLabel5.setText("No of TestCases :");
        jPanel1.add(jLabel5);

        noOfTestCases.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        noOfTestCases.setText("12");
        jPanel1.add(noOfTestCases);

        jLabel7.setText("No of Reusables :");
        jPanel1.add(jLabel7);

        noOfReusables.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        noOfReusables.setText("34");
        jPanel1.add(noOfReusables);

        jLabel9.setText("No of TestData :");
        jPanel1.add(jLabel9);

        noOfTestData.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        noOfTestData.setText("56");
        jPanel1.add(noOfTestData);

        openProject.setText("Open");
        openProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProjectActionPerformed(evt);
            }
        });

        projectName.setText("jTextField1");

        renameProject.setText("Rename");
        renameProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(projectLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openProject))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(projectName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(renameProject)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(projectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renameProject))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openProject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProjectActionPerformed
        DesktopApi.open(new File(projectLocation.getText()));
    }//GEN-LAST:event_openProjectActionPerformed

    private void renameProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameProjectActionPerformed
        if (!sMainFrame.getProject().getName().equals(projectName.getText().trim())) {
            if (Validator.isValidName(projectName.getText().trim())) {
                if(sMainFrame.renameProject(projectName.getText().trim())){
                    Notification.show("Project Renamed successfully");
                }else{
                    Notification.show("Couldn't rename the Project");
                }
            } else {
                Notification.show("Invalid Name " + projectName.getText());
            }
        }
    }//GEN-LAST:event_renameProjectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel noOfReusables;
    private javax.swing.JLabel noOfScenarios;
    private javax.swing.JLabel noOfTestCases;
    private javax.swing.JLabel noOfTestData;
    private javax.swing.JButton openProject;
    private javax.swing.JTextField projectLocation;
    private javax.swing.JTextField projectName;
    private javax.swing.JButton renameProject;
    // End of variables declaration//GEN-END:variables
}
